### ISSUE TITLE
Stop app from closing when user uses back button.

### ISSUE THREAD

**Issue by darkvoid32** [thunderbiscuit/padawan-wallet#164]
When the user uses the phone's back button the app closes. Is there a way to using fragments backstack, or another way to handle the onBackPressed logic.

**Comment by thunderbiscuit** [comment]
Isn't this standard behaviour? Trying a few other apps and they all do it. Unless I misunderstand your question?

**Comment by darkvoid32** [comment]
Sorry for not clarifying, since I thought that pressing the back button in certain fragments like the tutorials will lead back to tutorialsHome, or home page etc., instead of closing the app straight away.

**Comment by thunderbiscuit** [comment]
Ah yes ok I see what you mean!

Yes I do think there should be a way to customize that behaviour. I'm not actually sure how off the top of my head, but we should definitely keep this issue open. If you're interested in it feel free to look into it! No pressure. Otherwise we can also just keep it open to have it in mind for later.
