### ISSUE TITLE
CI keeps on failing

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#255]
The CI is failing because of changes made in the 0.10.0 release. Further digging is required to identify the reason and fix it.

**Comment by Prakhar-Agarwal-byte** [comment]
I will try to fix it

**Comment by thunderbiscuit** [comment]
See PR #283 for details. I don't know what changed in Compose for these tests to have passed in the past, but the snackbars are definitely not there in the Compose tree when the tests are expecting them. Removing them for now. I think those could be unit tests in the first place because they simply test whether wrong words are used in the recovery workflow.
