### ISSUE TITLE
Feature: The address should be present in the transaction details

### ISSUE THREAD

**Issue by Ayan-10** [thunderbiscuit/padawan-wallet#292]
In the transaction details section. The address of the send or received transaction should be mentioned.

**Comment by thunderbiscuit** [comment]
While this intuitively sounds like an easy thing to do, in practice it turns out that bitcoin transaction hide a lot of complexity that's hard to show to the user without being confusing. For example, _what_ addresses do we mean here? A single transaction can have many inputs (some coming from more than one wallet even), and many outputs (including change)! In the case of Padawan there is always only one receivers, but this is not true for all bitcoin transactions.

I'm not opposed to adding addresses, but I want to point out that this is a thorny issue in the world of bitcoin UX.

**Comment by Ayan-10** [comment]
Okay, It might be complex on the received transaction, I have to investigate that. But we can show the address in the send transactions in the Padawan wallet, as here we can send Bitcoin testnet to one receiver at a time. What do you think about that?
