### ISSUE TITLE
Publish app in F-Droid

### ISSUE THREAD

**Issue by emanuelb** [thunderbiscuit/padawan-wallet#84]
F-Droid URL: https://f-droid.org/
F-Droid Wikipedia: https://www.wikipedia.org/wiki/F-Droid

Contribution/Submit Applications: https://f-droid.org/en/contribute/#submit-applications
Inclusion Policy: https://f-droid.org/en/docs/Inclusion_Policy
Request For Packaging Tickets: https://gitlab.com/fdroid/rfp/issues

F-Droid is application & app store for android apps (alternative to Google Play) that accepts only FLOSS (free/libre and open-source) apps and doesn't require any account creation/login in order to download apps.

The requirements for being included into f-droid are here: https://f-droid.org/en/docs/Inclusion_Policy/

The process for getting an app published to f-droid is outlined here: https://f-droid.org/en/docs/Inclusion_How-To/ https://gitlab.com/fdroid/rfp#submission-queue https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

You can open a RFP (Request For Packaging) ticket here: https://gitlab.com/fdroid/rfp or an user can do so, provided you agree to include this app in F-droid (a comment to this issue is enough for it)

Some users don't have play-store on their devices as they are degoogled devices or don't create/use google account (using aurora store app https://auroraoss.com/ in anonymous mode (which is available on f-droid) is solution to still get apps from google-play) or using OS/custom ROMs that don't have it included, such as: (Some bundle f-droid by default)

https://grapheneos.org/ GrapheneOS
https://calyxos.org/ CalyxOS
https://lineageos.org/ LineageOS
https://lineage.microg.org/ LineageOS for microG
https://e.foundation/ /e/
https://www.replicant.us/ Replicant

Downloading APKs from official places like github releases https://github.com/thunderbiscuit/padawan-wallet/releases or website, or from unofficial sources like APK downloading sites https://apk.support or https://apkpure.com/ etc... will avoid the play-store/google dependency but it's lack automatic update mechanism unless it's built in into the application, F-Droid solve this.

Once the app is published into f-droid add the below image code into 
README.md to show that the app available on f-droid:
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png" alt="Get it on F-Droid" height="80">](https://f-droid.org/en/packages/org.fdroid.fdroid/)
`[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png" alt="Get it on F-Droid" height="80">](https://f-droid.org/en/packages/org.fdroid.fdroid/)`

**Comment by thunderbiscuit** [comment]
Dude I'm a huge F-Droid fan and publishing my app there has been one of my goals since the beginning! 🔥 🔥 Thanks for taking the time to open up an issue and checking out my app!

I need to do more research on this and maybe start asking questions on the forum, but one of the small little hiccup in the process right now as I understand it is that they handle the apk signatures (they basically build your app from source) for deployment on F-Droid. That's fine of course, but in my case I'm using the [bitcoindevkit](https://github.com/bitcoindevkit), which is a native Rust library with jni bindings for Android, and which I build locally and add in my localMaven() repository. Because the library is not yet deployed on Maven Central, I assume they won't be able to build the app themselves (unless I can add info on how to build the native lib locally, but that sounds like a lot of work for the F-Droid team).

So I'll ask around to see if there is a way around that. But it's possible that the bottleneck here for F-Droid might be on the bitcoindevkit side. And because they are rewriting all of their language bindings at the moment (including this bdk-jni library I'm using), I do think it will be a few months before it's ready to be published on maven central.

Do you happen to have experience with publishing apps on F-Droid? I'm just about ready to release a closed test version of the app on the Play Store, but I'd love to work on getting it ready for F-Droid in parallel while the bitcoindevkit guys do their thing.

**Comment by emanuelb** [comment]
no experience with publishing apps on F-Droid, but I read enough about the process & related RFP tickets so know to answer some of the questions.

1. F-Droid can reuse your app signing and not sign themself as long as the app is reproducible (build is reproducible), try to build the same tagged version twice and compare the results with diffoscope tool https://diffoscope.org/ , except the signing stuff there should be no other differences.
2. F-Droid doesn't allows binaries from unknown locations (not maven or tool from debian package, etc...) so if it's location is not whitelisted (places that ensure it's built from OSS, etc...) The build process would need to rebuild the library, which is ok (not much work involved except the build-commands to build it), they build all apps from source.
3. either way it's good to open the RFP ticket https://gitlab.com/fdroid/rfp even if there is some roadblocks (or more work needed) regarding the bitcoindevkit lib, as both people might look into the situation and offer guidelines, and their is automatic f-droid scanner that look for issues that need to be fixed, like adding fastlane structure (see: https://gitlab.com/snippets/1895688) and other stuff as well...

**Comment by thunderbiscuit** [comment]
Ok cheers! I'll look into that this week! Thanks for the tips.

**Comment by thunderbiscuit** [comment]
Closing this as I don't have the resources to work on this at the moment, but I'm adding it to the list of ideas for a 2.0 release!
